project:
  type: website
  output-dir: docs

website:
  comments: 
    utterances: 
      repo: quarto-dev/quarto-web
      theme: dark-blue
      issue-term: title
  reader-mode: true
  title: "Inquiring Minds Want to Know"
  navbar:
    background: dark
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com//rbarbanell
 
        
    
      
   
format:
  html:
    css: styles.css
    code-fold: true
    code-summary: "Here is the code"



