project:
  type: website
  output-dir: docs

website:
<<<<<<< HEAD
  comments: 
    utterances: 
      repo: quarto-dev/quarto-web
      theme: dark-blue
      issue-term: title
  reader-mode: true
  title: "Inquiring Minds Want to Know"
=======
 comments:
  giscus: 
    repo: quarto-dev/quarto-docs
  title: "main_webpage"
>>>>>>> 344c57f33e5386ce82bd5dbe8269500e10c7d3da
  navbar:
    background: dark
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com//rbarbanell
 
        
    
      
   
format:
  html:
    css: styles.css
    code-fold: true
    code-summary: "Here is the code"



