project:
  type: website

website:
 comments:
  giscus: 
    repo: quarto-dev/quarto-docs
  
title: "main_webpage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



